
package br.com.projeto.servico;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TesteSoapImplService", targetNamespace = "http://servico.projeto.com.br/", wsdlLocation = "http://localhost:8085/servico/cumprimento?wsdl")
public class TesteSoapImplService
    extends Service
{

    private final static URL TESTESOAPIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TESTESOAPIMPLSERVICE_EXCEPTION;
    private final static QName TESTESOAPIMPLSERVICE_QNAME = new QName("http://servico.projeto.com.br/", "TesteSoapImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8085/servico/cumprimento?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TESTESOAPIMPLSERVICE_WSDL_LOCATION = url;
        TESTESOAPIMPLSERVICE_EXCEPTION = e;
    }

    public TesteSoapImplService() {
        super(__getWsdlLocation(), TESTESOAPIMPLSERVICE_QNAME);
    }

    public TesteSoapImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TESTESOAPIMPLSERVICE_QNAME, features);
    }

    public TesteSoapImplService(URL wsdlLocation) {
        super(wsdlLocation, TESTESOAPIMPLSERVICE_QNAME);
    }

    public TesteSoapImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TESTESOAPIMPLSERVICE_QNAME, features);
    }

    public TesteSoapImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TesteSoapImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TesteSoap
     */
    @WebEndpoint(name = "TesteSoapImplPort")
    public TesteSoap getTesteSoapImplPort() {
        return super.getPort(new QName("http://servico.projeto.com.br/", "TesteSoapImplPort"), TesteSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TesteSoap
     */
    @WebEndpoint(name = "TesteSoapImplPort")
    public TesteSoap getTesteSoapImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servico.projeto.com.br/", "TesteSoapImplPort"), TesteSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TESTESOAPIMPLSERVICE_EXCEPTION!= null) {
            throw TESTESOAPIMPLSERVICE_EXCEPTION;
        }
        return TESTESOAPIMPLSERVICE_WSDL_LOCATION;
    }

}
