
package br.com.projeto.servico;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SEIExame", targetNamespace = "http://servico.projeto.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SEIExame {


    /**
     * 
     * @param arg0
     * @return
     *     returns br.com.projeto.servico.Exame
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarSoap", targetNamespace = "http://servico.projeto.com.br/", className = "br.com.projeto.servico.ConsultarSoap")
    @ResponseWrapper(localName = "consultarSoapResponse", targetNamespace = "http://servico.projeto.com.br/", className = "br.com.projeto.servico.ConsultarSoapResponse")
    @Action(input = "http://servico.projeto.com.br/SEIExame/consultarSoapRequest", output = "http://servico.projeto.com.br/SEIExame/consultarSoapResponse")
    public Exame consultarSoap(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<br.com.projeto.servico.Exame>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultar", targetNamespace = "http://servico.projeto.com.br/", className = "br.com.projeto.servico.Consultar")
    @ResponseWrapper(localName = "consultarResponse", targetNamespace = "http://servico.projeto.com.br/", className = "br.com.projeto.servico.ConsultarResponse")
    @Action(input = "http://servico.projeto.com.br/SEIExame/consultarRequest", output = "http://servico.projeto.com.br/SEIExame/consultarResponse")
    public List<Exame> consultar();

}
